
name = input("Введите ФИО исследователя: ")
date = input("Введите дату (ДД.ММ.ГГГГ): ")
experiment_name = input("Введите название эксперимента: ")
conclusion = input("Введите вывод по эксперименту: ")
print("=== Заполнение лабораторного журнала ===")
print(f"Имя: {name}\nДата: {date}\nЭксперимент: {experiment_name}")
print("-_-" * 14)
print(f" Вывод: {conclusion}")
print("-_-" * 14)